# Generated by Django 4.1.7 on 2024-05-17 19:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Controlling', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Admin',
        ),
    ]
