# Generated by Django 4.1.7 on 2024-05-15 13:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Controlling', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='borrowing',
            name='BookId',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Controlling.book'),
        ),
    ]
