# Generated by Django 4.1.7 on 2024-05-15 15:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Controlling', '0002_borrowing_bookid'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='Avilable',
            new_name='Available',
        ),
    ]
